### PR TITLE
Add a kill_dummy command to "respawn/selfkill" the dummy

### PR DESCRIPTION
**Pull request by gwilherm**
I saw that CGameClient::SendKill() has a unused argument "int ClientID", it gave me the idea to add a kill_dummy command.

### CODE REVIEW

**Comment by def-** [comment]
What's the purpose? And then we would also need other controls for the dummy.

**Comment by gwilherm** [comment]
When failing in dummy race, it's easier to respawn both at the same time with a binding like :
bind f "kill; kill_dummy"

**Comment by Sonix-** [comment]
If you play in a locked team, you can kill both anyway

**Comment by gwilherm** [comment]
Oh, you're right

**Pull request closed without merging**
