### PR TITLE
Download script

### PR DESCRIPTION
**Pull request by Zwelf**
See issue: #256
Created the python side of the download script. Someone else could create the lua side. @Henningstone would you like to do that?

### CODE REVIEW

**Comment by Henningstone** [comment]
Sure :)
I will pull-request on your repo though, because that stuff belongs together. You can then merge it.

**Comment by Henningstone** [comment]
Ok, finished it. It is completely different than I did it for 0.7 (because the bam.lua is sightly different), but I think it's even a bit more elegant that way :)

**Comment by def-** [comment]
Hm, having a bunch of zip files in a git repository is not ideal, I wanted the actual library files and headers there. Also, why is only Windows supported? Use this for Python 2+3 support:
```python
try:
    import urllib.request as urllib_request # for python 3
except ImportError:
    import urllib2 as urllib_request # for python 2
```
I tried to fix the PR, but didn't manage.

Also, I didn't see when you added the most recent commit, so I didn't notice this was ready 8 days ago. Github only notifies of new comments, not commits, so write something when it's ready please.

**Comment by Henningstone** [comment]
Windows only because on linux you can just use your favourite packet manager to install all the stuff. One line in the Terminal and it's done. Most people on linux should have it already, thought.

Supporting both python version is a good idea :) But this is @Zwelf 's part.

**Comment by def-** [comment]
Well, I don't think it should be Windows only, since we already have all the libraries compiled and we need them for the official ddnet releases anyway. Same for Mac.

**Comment by Zwelf** [comment]
> Made a repo of how I want ddnet-libs to look, ideally the scripts would work with exactly that:
Hm, making the libs as folders in a repository isn't easy to download, because you can't download a single folder.
What do you think of making for each ddnet-lib a branch?

**Comment by def-** [comment]
> What do you think of making for each ddnet-lib a branch?

Sounds a bit clunky, not sure how best to solve this.

**Comment by Zwelf** [comment]
Okay, I will write a script this week which is working with this repository, but then there will only be the possible to download all libs.
One problem is remaining: When the libs get updated, the local libs should get updated as well.
My idea of solving that: In this repository is a file indicating the version. In the lua file stands the version, which is wanted and give this version to the download script.
When the libs get updated: Then the indicating file and the lua file has to be updated and there has to be an new tag on the git repository.

**Comment by def-** [comment]
> Okay, I will write a script this week which is working with this repository, but then there will only be the possible to download all libs.

That's no improvement over the current state of affairs then.

**Comment by Zwelf** [comment]
I improved the download script now. It is python 2 compatible and download the wanted version. It has to download all libs at the same time and I added all precompiled libs from Linux and Mac.

**Pull request merged**
