### PR TITLE
Use the new callback. Make sure filesize < INT_MAX.

### PR DESCRIPTION
**Pull request by Learath2**

### CODE REVIEW

**Comment by MyNewBie** [comment]
not added in source ?

**Comment by def-** [comment]
huh?

**Comment by MyNewBie** [comment]
i mean do you forgot add  " Use the new callback. Make sure filesize < INT_MAX. "  to ddnet commits ? I cant find it in ddnet commits !

**Comment by def-** [comment]
Nope, I reverted this again because I couldn't get it to build on Android.

**Pull request merged**
