### PR TITLE
update simplified_chinese and add simplified_chinese to language list

### PR DESCRIPTION
**Pull request by awaysoft**

### CODE REVIEW

**Comment by def-** [comment]
I would really like to add this, but a 10 MB font file is still pretty big. It would double our client size.

**Comment by awaysoft** [comment]
I merge WenQuanYI Microhei and DejaVuSans,I don't know why it become 10MB, WenQuanYi Microhei is only 5MB(http://sourceforge.net/projects/wqy/files/wqy-microhei/0.2.0-beta/wqy-microhei-0.2.0-beta.tar.gz/download)
Because Chinese charset have more than 20000 charsets, font size may not be small.
Opensource Chinese font I know only:
WenQuanYi ZenHei(http://sourceforge.net/projects/wqy/)
WenQuanYi MicroHei(http://sourceforge.net/projects/wqy/)
Source Han Sans(http://sourceforge.net/adobe/source-han-sans/)

I have replace font and make a zip archive(win32),it is 17.3MB, only bigger 3MB.

**Comment by def-** [comment]
I can reduce to file size to 3.4 MB, but the next problem is that the client takes a few seconds to start and needs 16 MB more memory.

**Comment by awaysoft** [comment]
Sad to hear that, but this font is the smallest font, if has no font, ddnet cannot see any Chinese.
I Don't know what other's think,but I don't mind a little slow on start and more memory.
Or maybe ddnet can load system font?

**Comment by def-** [comment]
I think the text rendering needs to be optimized for this to work well. While playing I noticed lags caused by the bigger font, when someone new joins or writes something.

**Comment by awaysoft** [comment]
What do you mean? I can't write Chinese or can't write in ddnet?

**Comment by def-** [comment]
In DDNet of course, because we use SDL 1.2 instead of SDL 2 with its new text input. I believe you that you can write Chinese in general.

**Comment by awaysoft** [comment]
I can write in DDnet on Linux System using fcitx input method,but can't write on Windows,but there's a mod of teeworlds can write chinese on windows using SDL2, some players using this and write chinese.
If there is no font,I can't read what they write.

**Comment by MyNewBie** [comment]
see this @awaysoft https://www.teeworlds.com/forum/viewtopic.php?id=10838

**Comment by awaysoft** [comment]
yeah,I know this, and many people using this one in China.

**Comment by awaysoft** [comment]
In language file, I only find teeworlds's string, no found any string about ddnet?

**Comment by def-** [comment]
None of the DDNet specific stuff is localized. I believe that localization is too much work and not worth it. I remember playing games in English all the time when I was a kid, without understanding a word, and it didn't hurt.

**Comment by TsFreddie** [comment]
Well, CJK fonts do need additional 10+MB memory. But the more serious problem is that every time FreeType pull out a font and let it render into a texture, it cost almost 0.1 seconds for each character, I don't really recommend put CJK fonts for now if we still using this rendering method.

**Comment by TsFreddie** [comment]
BTW, the string that you should translate is defined in the source code using Localize(string) function,  and the code won't update those string to the language file by itself

**Pull request closed without merging**
