### PR TITLE
Save server settings within the map

### PR DESCRIPTION
**Pull request by heinrich5991**
In order to be backwards-compatible, the map settings (`maps/<map>.cfg`) are put into the map upon loading. Afterwards the map settings are safely executed, i.e. they can only change whitelisted configs. When the next map is loaded, the previous settings are restored.

### CODE REVIEW

**Comment by def-** [comment]
Oops, didn't know renaming the branch would close this.

**Comment by heinrich5991** [comment]
Should I reopen this pull request? Have you already merged it?

**Comment by def-** [comment]
Yeah, reopen would make sense, I made some comments on IRC, but you may have missed them.

**Comment by heinrich5991** [comment]
@def- Sure. Should I completely drop the part where the server changes the map?

**Comment by def-** [comment]
I guess. Maybe it makes sense in some scenarios, but I wouldn't want it on official DDNet servers. And maintaining more code is usually bad.

At least we need a solution for these problems:

- How to translate all the current maps
- How to set settings while mapping
- How to edit a map config without client editor

**Pull request closed without merging**
